version: "3.8"

####################
# Réseaux & données
####################
networks:
  traefik:
    external: true   # doit exister : docker network create -d overlay traefik --attachable

configs:
  traefik_static:
    file: ./traefik.yml   # config statique (entryPoints, TLS, providers, API, log)

####################
# Services
####################
services:

  # Proxy Docker sécurisé pour exposer les infos Swarm à Traefik
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    environment:
      # Autorisations minimales pour Traefik
      CONTAINERS: "1"
      SERVICES:   "1"
      SWARM:      "1"
      NETWORKS:   "1"
      TASKS:      "1"
      NODES:      "1"
      INFO:       "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: [traefik]
    deploy:
      mode: global
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.role == manager

  # Traefik en mode actif-actif sur tous les managers
  traefik:
    image: traefik:latest
    networks: [traefik]
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8000
        published: 8000
        protocol: tcp
        mode: ingress   # dashboard
    configs:
      - source: traefik_static
        target: /etc/traefik/traefik.yml
        mode: 0444   # lecture seule
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

